/*
 * Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.config.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.config.model.Industry;
import com.smartrecruiters.api.config.model.Location;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CompanyConfiguration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T11:44:28.029340+01:00[Europe/Rome]")
public class CompanyConfiguration {
  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private Location location;

  public static final String SERIALIZED_NAME_WEBSITE = "website";
  @SerializedName(SERIALIZED_NAME_WEBSITE)
  private String website;

  public static final String SERIALIZED_NAME_INDUSTRY = "industry";
  @SerializedName(SERIALIZED_NAME_INDUSTRY)
  private Industry industry;

  public static final String SERIALIZED_NAME_LOGO = "logo";
  @SerializedName(SERIALIZED_NAME_LOGO)
  private String logo;


  public CompanyConfiguration identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Identifier of a company.
   * @return identifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifier of a company.")

  public String getIdentifier() {
    return identifier;
  }



  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public CompanyConfiguration name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Company name.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Company name.")

  public String getName() {
    return name;
  }



  public void setName(String name) {
    this.name = name;
  }


  public CompanyConfiguration location(Location location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Location getLocation() {
    return location;
  }



  public void setLocation(Location location) {
    this.location = location;
  }


  public CompanyConfiguration website(String website) {
    
    this.website = website;
    return this;
  }

   /**
   * URL to company website.
   * @return website
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL to company website.")

  public String getWebsite() {
    return website;
  }



  public void setWebsite(String website) {
    this.website = website;
  }


  public CompanyConfiguration industry(Industry industry) {
    
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Industry getIndustry() {
    return industry;
  }



  public void setIndustry(Industry industry) {
    this.industry = industry;
  }


  public CompanyConfiguration logo(String logo) {
    
    this.logo = logo;
    return this;
  }

   /**
   * URL to company logo.
   * @return logo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL to company logo.")

  public String getLogo() {
    return logo;
  }



  public void setLogo(String logo) {
    this.logo = logo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyConfiguration companyConfiguration = (CompanyConfiguration) o;
    return Objects.equals(this.identifier, companyConfiguration.identifier) &&
        Objects.equals(this.name, companyConfiguration.name) &&
        Objects.equals(this.location, companyConfiguration.location) &&
        Objects.equals(this.website, companyConfiguration.website) &&
        Objects.equals(this.industry, companyConfiguration.industry) &&
        Objects.equals(this.logo, companyConfiguration.logo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, name, location, website, industry, logo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyConfiguration {\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

