/*
 * Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.config.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.config.model.RelationJobPropertyValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DependentJobPropertyValuesRelation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T11:44:28.029340+01:00[Europe/Rome]")
public class DependentJobPropertyValuesRelation {
  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private RelationJobPropertyValue parent;

  public static final String SERIALIZED_NAME_VALUES = "values";
  @SerializedName(SERIALIZED_NAME_VALUES)
  private List<RelationJobPropertyValue> values = new ArrayList<RelationJobPropertyValue>();


  public DependentJobPropertyValuesRelation parent(RelationJobPropertyValue parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @ApiModelProperty(required = true, value = "")

  public RelationJobPropertyValue getParent() {
    return parent;
  }



  public void setParent(RelationJobPropertyValue parent) {
    this.parent = parent;
  }


  public DependentJobPropertyValuesRelation values(List<RelationJobPropertyValue> values) {
    
    this.values = values;
    return this;
  }

  public DependentJobPropertyValuesRelation addValuesItem(RelationJobPropertyValue valuesItem) {
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  @ApiModelProperty(required = true, value = "")

  public List<RelationJobPropertyValue> getValues() {
    return values;
  }



  public void setValues(List<RelationJobPropertyValue> values) {
    this.values = values;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DependentJobPropertyValuesRelation dependentJobPropertyValuesRelation = (DependentJobPropertyValuesRelation) o;
    return Objects.equals(this.parent, dependentJobPropertyValuesRelation.parent) &&
        Objects.equals(this.values, dependentJobPropertyValuesRelation.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parent, values);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DependentJobPropertyValuesRelation {\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

