/*
 * Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.config.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HiringProcessSubStatuses
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T11:44:28.029340+01:00[Europe/Rome]")
public class HiringProcessSubStatuses {
  public static final String SERIALIZED_NAME_I_N_R_E_V_I_E_W = "IN_REVIEW";
  @SerializedName(SERIALIZED_NAME_I_N_R_E_V_I_E_W)
  private List<String> IN_REVIEW = null;

  public static final String SERIALIZED_NAME_I_N_T_E_R_V_I_E_W = "INTERVIEW";
  @SerializedName(SERIALIZED_NAME_I_N_T_E_R_V_I_E_W)
  private List<String> INTERVIEW = null;

  public static final String SERIALIZED_NAME_O_F_F_E_R_E_D = "OFFERED";
  @SerializedName(SERIALIZED_NAME_O_F_F_E_R_E_D)
  private List<String> OFFERED = null;


  public HiringProcessSubStatuses IN_REVIEW(List<String> IN_REVIEW) {
    
    this.IN_REVIEW = IN_REVIEW;
    return this;
  }

  public HiringProcessSubStatuses addINREVIEWItem(String IN_REVIEWItem) {
    if (this.IN_REVIEW == null) {
      this.IN_REVIEW = new ArrayList<String>();
    }
    this.IN_REVIEW.add(IN_REVIEWItem);
    return this;
  }

   /**
   * Get IN_REVIEW
   * @return IN_REVIEW
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getINREVIEW() {
    return IN_REVIEW;
  }



  public void setINREVIEW(List<String> IN_REVIEW) {
    this.IN_REVIEW = IN_REVIEW;
  }


  public HiringProcessSubStatuses INTERVIEW(List<String> INTERVIEW) {
    
    this.INTERVIEW = INTERVIEW;
    return this;
  }

  public HiringProcessSubStatuses addINTERVIEWItem(String INTERVIEWItem) {
    if (this.INTERVIEW == null) {
      this.INTERVIEW = new ArrayList<String>();
    }
    this.INTERVIEW.add(INTERVIEWItem);
    return this;
  }

   /**
   * Get INTERVIEW
   * @return INTERVIEW
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getINTERVIEW() {
    return INTERVIEW;
  }



  public void setINTERVIEW(List<String> INTERVIEW) {
    this.INTERVIEW = INTERVIEW;
  }


  public HiringProcessSubStatuses OFFERED(List<String> OFFERED) {
    
    this.OFFERED = OFFERED;
    return this;
  }

  public HiringProcessSubStatuses addOFFEREDItem(String OFFEREDItem) {
    if (this.OFFERED == null) {
      this.OFFERED = new ArrayList<String>();
    }
    this.OFFERED.add(OFFEREDItem);
    return this;
  }

   /**
   * Get OFFERED
   * @return OFFERED
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getOFFERED() {
    return OFFERED;
  }



  public void setOFFERED(List<String> OFFERED) {
    this.OFFERED = OFFERED;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HiringProcessSubStatuses hiringProcessSubStatuses = (HiringProcessSubStatuses) o;
    return Objects.equals(this.IN_REVIEW, hiringProcessSubStatuses.IN_REVIEW) &&
        Objects.equals(this.INTERVIEW, hiringProcessSubStatuses.INTERVIEW) &&
        Objects.equals(this.OFFERED, hiringProcessSubStatuses.OFFERED);
  }

  @Override
  public int hashCode() {
    return Objects.hash(IN_REVIEW, INTERVIEW, OFFERED);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HiringProcessSubStatuses {\n");
    sb.append("    IN_REVIEW: ").append(toIndentedString(IN_REVIEW)).append("\n");
    sb.append("    INTERVIEW: ").append(toIndentedString(INTERVIEW)).append("\n");
    sb.append("    OFFERED: ").append(toIndentedString(OFFERED)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

