/*
 * Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.config.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.config.model.Identifiable;
import com.smartrecruiters.api.config.model.SourceTypesActions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SourceTypesContent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T11:44:28.029340+01:00[Europe/Rome]")
public class SourceTypesContent {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private SourceTypesActions actions;

  public static final String SERIALIZED_NAME_SUBTYPES = "subtypes";
  @SerializedName(SERIALIZED_NAME_SUBTYPES)
  private List<Identifiable> subtypes = new ArrayList<Identifiable>();


  public SourceTypesContent id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public SourceTypesContent label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLabel() {
    return label;
  }



  public void setLabel(String label) {
    this.label = label;
  }


  public SourceTypesContent actions(SourceTypesActions actions) {
    
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(required = true, value = "")

  public SourceTypesActions getActions() {
    return actions;
  }



  public void setActions(SourceTypesActions actions) {
    this.actions = actions;
  }


  public SourceTypesContent subtypes(List<Identifiable> subtypes) {
    
    this.subtypes = subtypes;
    return this;
  }

  public SourceTypesContent addSubtypesItem(Identifiable subtypesItem) {
    this.subtypes.add(subtypesItem);
    return this;
  }

   /**
   * Get subtypes
   * @return subtypes
  **/
  @ApiModelProperty(required = true, value = "")

  public List<Identifiable> getSubtypes() {
    return subtypes;
  }



  public void setSubtypes(List<Identifiable> subtypes) {
    this.subtypes = subtypes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceTypesContent sourceTypesContent = (SourceTypesContent) o;
    return Objects.equals(this.id, sourceTypesContent.id) &&
        Objects.equals(this.label, sourceTypesContent.label) &&
        Objects.equals(this.actions, sourceTypesContent.actions) &&
        Objects.equals(this.subtypes, sourceTypesContent.subtypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, actions, subtypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceTypesContent {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    subtypes: ").append(toIndentedString(subtypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

